### ISSUE TITLE
ng-build no funciona

### ISSUE THREAD

**Issue by jairoGilC** [kutyel/famous-painters#1]
He clonado el proyecto ejecute `npm install` para actualizar dependencias sin embargo cuando corri `ng build` para probar la aplicación como seria en producción. abro la carpeta ./dist y abro index.html y me aparece el siguiente error

```
ReferenceError: System is not defined
```

**Comment by kutyel** [comment]
Para ejecutar el build y mostrar el resultado en un server local tienes que usar el comando:

``` sh
ng serve
```

Con eso debería bastar. 😉
